"""Synthetic data generators for testing.

This module provides utilities to generate synthetic gridded data and
geometry data for testing the pairing, plotting, and statistics
components without requiring external datasets.

Usage:
    from davinci_monet.tests.synthetic import (
        create_dataset_dataset,
        create_point_geometries,
        create_track_geometries,
        PerfectMatchScenario,
    )

    # Generate synthetic gridded data
    dataset = create_dataset_dataset(
        variables=["O3", "PM25"],
        time_range=("2024-01-01", "2024-01-03"),
    )

    # Generate matching geometry data
    geometry = create_point_geometries(
        n_sites=10,
        variables=["O3", "PM25"],
        time_range=("2024-01-01", "2024-01-03"),
    )
"""

from davinci_monet.tests.synthetic.aerosol_tuning import (
    ACCEPTANCE_EXCLUDED_FRACTION_MAX,
    ACCEPTANCE_MAX_ELAPSED_SECONDS,
    ACCEPTANCE_MAX_PEAK_RSS_BYTES,
    ACCEPTANCE_SCHEMA,
    ACCEPTANCE_SEED_COUNT,
    CALIBRATION_SCHEMA,
    CALIBRATION_SEED,
    CALIBRATION_SPLIT,
    DEFAULT_AEROSOL_SPECIES,
    EVIDENCE_HASH_KEYS,
    FROZEN_CALIBRATION_FILENAME,
    FROZEN_CALIBRATION_SHA256,
    NAMED_STREAMS,
    NULL_FRACTION_MAX,
    NULL_SEED,
    RANKING_ORDER,
    RECOVERY_THRESHOLDS,
    AnalyticTemporalTarget,
    CalibrationCandidate,
    CalibrationEvidence,
    CandidateMetrics,
    PipelineExecutor,
    ScientificPolicy,
    ShiftedLogResult,
    SyntheticAcceptancePlan,
    SyntheticCalibrationRecord,
    SyntheticTuningBundle,
    SyntheticTuningSpec,
    analytic_temporal_filter_target,
    area_weighted_regrid_oracle,
    build_synthetic_acceptance_plan,
    calibration_code_sha256,
    calibration_policy_candidates,
    calibration_record_sha256,
    candidate_rejection_reasons,
    canonical_calibration_json,
    evaluate_null_control,
    evaluate_synthetic_recovery_gate,
    generate_aerosol_tuning_bundle,
    load_calibration_record,
    local_overpass_oracle,
    log_time_interpolation_oracle,
    named_rng,
    named_stream_id,
    optical_aod_oracle,
    periodic_bilinear_oracle,
    render_synthetic_acceptance_configs,
    run_frozen_calibration,
    run_synthetic_acceptance,
    scientific_dataset_hash,
    select_calibration_policy,
    shifted_log_ratio_oracle,
    validate_frozen_calibration_record,
    verify_calibration_record,
    write_aerosol_tuning_bundle,
    write_calibration_record,
)
from davinci_monet.tests.synthetic.datasets import (
    DatasetConfig,
    create_dataset_dataset,
    create_point_geometries,
    create_profile_geometries,
    create_swath_geometries,
    create_track_geometries,
    create_variable_field,
)
from davinci_monet.tests.synthetic.generators import (
    Domain,
    TimeConfig,
    create_coordinate_grid,
    create_time_axis,
    random_locations_in_domain,
)
from davinci_monet.tests.synthetic.scenarios import (
    BiasScenario,
    MismatchScenario,
    PerfectMatchScenario,
    Scenario,
)

__all__ = [
    # Aerosol tuning
    "ACCEPTANCE_EXCLUDED_FRACTION_MAX",
    "ACCEPTANCE_MAX_ELAPSED_SECONDS",
    "ACCEPTANCE_MAX_PEAK_RSS_BYTES",
    "ACCEPTANCE_SCHEMA",
    "ACCEPTANCE_SEED_COUNT",
    "CALIBRATION_SCHEMA",
    "CALIBRATION_SEED",
    "CALIBRATION_SPLIT",
    "EVIDENCE_HASH_KEYS",
    "FROZEN_CALIBRATION_FILENAME",
    "FROZEN_CALIBRATION_SHA256",
    "NULL_FRACTION_MAX",
    "NULL_SEED",
    "PipelineExecutor",
    "RANKING_ORDER",
    "RECOVERY_THRESHOLDS",
    "AnalyticTemporalTarget",
    "CalibrationCandidate",
    "CalibrationEvidence",
    "CandidateMetrics",
    "DEFAULT_AEROSOL_SPECIES",
    "NAMED_STREAMS",
    "ShiftedLogResult",
    "SyntheticTuningBundle",
    "SyntheticTuningSpec",
    "SyntheticAcceptancePlan",
    "ScientificPolicy",
    "SyntheticCalibrationRecord",
    "area_weighted_regrid_oracle",
    "analytic_temporal_filter_target",
    "build_synthetic_acceptance_plan",
    "calibration_code_sha256",
    "calibration_policy_candidates",
    "calibration_record_sha256",
    "candidate_rejection_reasons",
    "canonical_calibration_json",
    "evaluate_null_control",
    "evaluate_synthetic_recovery_gate",
    "generate_aerosol_tuning_bundle",
    "local_overpass_oracle",
    "load_calibration_record",
    "log_time_interpolation_oracle",
    "named_rng",
    "named_stream_id",
    "optical_aod_oracle",
    "periodic_bilinear_oracle",
    "render_synthetic_acceptance_configs",
    "run_frozen_calibration",
    "run_synthetic_acceptance",
    "select_calibration_policy",
    "scientific_dataset_hash",
    "shifted_log_ratio_oracle",
    "verify_calibration_record",
    "validate_frozen_calibration_record",
    "write_aerosol_tuning_bundle",
    "write_calibration_record",
    # Generators
    "Domain",
    "TimeConfig",
    "create_coordinate_grid",
    "create_time_axis",
    "random_locations_in_domain",
    # Datasets
    "DatasetConfig",
    "create_dataset_dataset",
    "create_variable_field",
    # Datasets
    "create_point_geometries",
    "create_track_geometries",
    "create_profile_geometries",
    "create_swath_geometries",
    # Scenarios
    "Scenario",
    "PerfectMatchScenario",
    "BiasScenario",
    "MismatchScenario",
]
