"""Public API for coupled synthetic aerosol-tuning inputs and independent oracles.

Implementation is split into cohesive private modules so the generator remains reviewable.
Generator and oracle modules do not import production FABLE preprocessing, projection,
scaling, interpolation, wavelet-filter, or writer helpers. Calibration and acceptance runners
intentionally exercise the production pipeline.
"""

from davinci_monet.tests.synthetic._aerosol_acceptance import (
    ACCEPTANCE_EXCLUDED_FRACTION_MAX,
    ACCEPTANCE_MAX_ELAPSED_SECONDS,
    ACCEPTANCE_MAX_PEAK_RSS_BYTES,
    ACCEPTANCE_SCHEMA,
    ACCEPTANCE_SEED_COUNT,
    FROZEN_CALIBRATION_FILENAME,
    FROZEN_CALIBRATION_SHA256,
    RECOVERY_THRESHOLDS,
    PipelineExecutor,
    SyntheticAcceptancePlan,
    build_synthetic_acceptance_plan,
    evaluate_synthetic_recovery_gate,
    render_synthetic_acceptance_configs,
    run_synthetic_acceptance,
)
from davinci_monet.tests.synthetic._aerosol_contracts import (
    DEFAULT_AEROSOL_SPECIES,
    NAMED_STREAMS,
    SCHEMA_VERSION,
    SENSORS,
    ShiftedLogResult,
    SyntheticTuningBundle,
    SyntheticTuningSpec,
    named_rng,
    named_stream_id,
)
from davinci_monet.tests.synthetic._aerosol_io import (
    generate_aerosol_tuning_bundle,
    scientific_dataset_hash,
    write_aerosol_tuning_bundle,
)
from davinci_monet.tests.synthetic._aerosol_oracles import (
    area_weighted_regrid_oracle,
    local_overpass_oracle,
    log_time_interpolation_oracle,
    optical_aod_oracle,
    periodic_bilinear_oracle,
    shifted_log_ratio_oracle,
)
from davinci_monet.tests.synthetic._aerosol_temporal import (
    AnalyticTemporalTarget,
    analytic_temporal_filter_target,
)
from davinci_monet.tests.synthetic.aerosol_calibration import (
    CALIBRATION_SCHEMA,
    EVIDENCE_HASH_KEYS,
    NULL_FRACTION_MAX,
    RANKING_ORDER,
    CalibrationCandidate,
    CalibrationEvidence,
    CandidateMetrics,
    ScientificPolicy,
    SyntheticCalibrationRecord,
    calibration_record_sha256,
    candidate_rejection_reasons,
    canonical_calibration_json,
    load_calibration_record,
    select_calibration_policy,
    verify_calibration_record,
    write_calibration_record,
)
from davinci_monet.tests.synthetic.fable_calibration_identity import (
    CALIBRATION_SEED,
    CALIBRATION_SPLIT,
    NULL_SEED,
    calibration_code_sha256,
    calibration_policy_candidates,
    validate_frozen_calibration_record,
)
from davinci_monet.tests.synthetic.fable_calibration_runner import (
    evaluate_null_control,
    run_frozen_calibration,
)

__all__ = [
    "ACCEPTANCE_EXCLUDED_FRACTION_MAX",
    "ACCEPTANCE_MAX_ELAPSED_SECONDS",
    "ACCEPTANCE_MAX_PEAK_RSS_BYTES",
    "DEFAULT_AEROSOL_SPECIES",
    "ACCEPTANCE_SCHEMA",
    "ACCEPTANCE_SEED_COUNT",
    "CALIBRATION_SCHEMA",
    "CALIBRATION_SEED",
    "CALIBRATION_SPLIT",
    "EVIDENCE_HASH_KEYS",
    "FROZEN_CALIBRATION_FILENAME",
    "FROZEN_CALIBRATION_SHA256",
    "NULL_FRACTION_MAX",
    "NULL_SEED",
    "NAMED_STREAMS",
    "PipelineExecutor",
    "RANKING_ORDER",
    "RECOVERY_THRESHOLDS",
    "SCHEMA_VERSION",
    "SENSORS",
    "AnalyticTemporalTarget",
    "ShiftedLogResult",
    "SyntheticTuningBundle",
    "SyntheticTuningSpec",
    "SyntheticAcceptancePlan",
    "CalibrationCandidate",
    "CalibrationEvidence",
    "CandidateMetrics",
    "ScientificPolicy",
    "SyntheticCalibrationRecord",
    "area_weighted_regrid_oracle",
    "analytic_temporal_filter_target",
    "build_synthetic_acceptance_plan",
    "calibration_record_sha256",
    "calibration_code_sha256",
    "calibration_policy_candidates",
    "candidate_rejection_reasons",
    "canonical_calibration_json",
    "evaluate_null_control",
    "evaluate_synthetic_recovery_gate",
    "generate_aerosol_tuning_bundle",
    "local_overpass_oracle",
    "load_calibration_record",
    "log_time_interpolation_oracle",
    "named_rng",
    "named_stream_id",
    "optical_aod_oracle",
    "periodic_bilinear_oracle",
    "render_synthetic_acceptance_configs",
    "run_synthetic_acceptance",
    "run_frozen_calibration",
    "select_calibration_policy",
    "scientific_dataset_hash",
    "shifted_log_ratio_oracle",
    "verify_calibration_record",
    "validate_frozen_calibration_record",
    "write_calibration_record",
    "write_aerosol_tuning_bundle",
]
